// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/5/2026, 6:36:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/felixchima/Desktop/Backoffice-app/altisry-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/plugins/**/*.{js,ts,mjs}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/composables/**/*.{js,ts,mjs}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/utils/**/*.{js,ts,mjs}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/felixchima/Desktop/Backoffice-app/altisry-website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;